@baseurl = http://localhost:3000

### Find All
GET {{baseurl}}/user HTTP/1.1

### Create
POST {{baseurl}}/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
  "name": "Luisa Santos",
  "username":"Luisa",
  "email":"luisa@gmail.com",
  "password":"12345",
  "avatar":"https://github.com/account",
  "background":"bg"
}

### Find By Id
GET {{baseurl}}/user/63e2315613d8e3692495533d

### Update
PATCH  {{baseurl}}/user/63e2315613d8e3692495533d
Content-Type: application/json

{
  "name": "Luisa Santos Vasco",
  "username":"Luisa",
  "email":"luisa@gmail.com",
  "password":"12345",
  "avatar":"https://github.com/account",
  "background":"bg"
}
